version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  Beforeinstall:
    - location: stop_server.sh
      timeout: 300
      runas: root
  Afterinstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
